=== Valord01/coursersa-web/XmlTest/NewXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.example.org/NewXMLSchema" 
xmlns:tns="http://www.example.org/NewXMLSchema" 
elementFormDefault="qualified">
<complexType name="Library">
         <sequence>
            <element name = "Libranian" type="tns:librarianType" 
            maxOccurs="3" minOccurs="1"
            />
         </sequence>
   </complexType>
   <complexType name = "librarianType">
      <sequence>
         <element name = "Firstname" type = "string"/>
         <element name = "Lastname" type = "string"/>
         <element name = "Nickname" type = "string"/>
         <element name = "Post" type="string"/>
         <element name = "Desc_of_job" type = "string"/>
         <element name = "Qualification" type = "string"/>
          <element name = "Salary" type = "tns:MS"/>
      </sequence>
      <attribute name = 'LibrID' type ="ID" use="required"/>
   </complexType>
   <element name="globalLibrary" type="tns:Library"></element>
  <simpleType name="MS">
  <restriction base="integer">
  <minExclusive value="30000"></minExclusive>
   <maxExclusive value="80000"></maxExclusive>
  </restriction>
  </simpleType>
</schema>

=== Valord01/coursersa-web/XmlTest/NewFile21.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="NewStylesheet.xsl"?>
<tns:globalLibrary xmlns:tns="http://www.example.org/NewXMLSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/NewXMLSchema NewXMLSchema.xsd">

  <tns:Libranian LibrID="idvalue0">
    <tns:Firstname>tns:Firstname</tns:Firstname>
    <tns:Lastname>tns:Lastname</tns:Lastname>
    <tns:Nickname>tns:Nickname</tns:Nickname>
    <tns:Post>1</tns:Post>
    <tns:Desc_of_job>1</tns:Desc_of_job>
    <tns:Qualification>1</tns:Qualification>
    <tns:Salary>35000</tns:Salary>
  </tns:Libranian>
</tns:globalLibrary>
